-- Insertion dans la table `covers`
INSERT INTO covers (artist, album, filename, answer_artist, answer_album, genre, langue, date_publication) VALUES
('AC/DC', 'Back in Black', 'AC_DC - Back in Black.jpg', 'ac/dc', 'back in black', 'arena rock', 'eng', '1987-02'),
('Pink Floyd', 'The Dark Side of the Moon', 'Pink Floyd - The Dark Side of the Moon.jpg', 'pink floyd', 'the dark side of the moon', 'ambient', 'eng', NULL),
('The Beatles', 'Abbey Road', 'The Beatles - Abbey Road.jpg', 'the beatles', 'abbey road', 'ambient', 'eng', '1987-10'),
('Fleetwood Mac', 'Rumours', 'Fleetwood Mac - Rumours.jpg', 'fleetwood mac', 'rumours', 'blues', 'eng', '1977'),
('Nirvana', 'Nevermind', 'Nirvana - Nevermind.jpg', 'nirvana', 'nevermind', 'alternative rock', 'eng', NULL),
('Prince', 'Purple Rain', 'Prince - Purple Rain.jpg', 'prince', 'purple rain', 'contemporary r&b', 'eng', NULL),
('Bob Dylan', 'Blood on the Tracks', 'Bob Dylan - Blood on the Tracks.jpg', 'bob dylan', 'blood on the tracks', 'blues rock', 'eng', '2004-09-23'),
('Lauryn Hill', 'The Miseducation of Lauryn Hill', 'Lauryn Hill - The Miseducation of Lauryn Hill.jpg', 'lauryn hill', 'the miseducation of lauryn hill', 'alternative hip hop', 'eng', '1998-08-25'),
('The Beatles', 'Revolver', 'The Beatles - Revolver.jpg', 'the beatles', 'revolver', 'beat music', 'eng', '1987-04-30'),
('Marvin Gaye', 'What''s Going On', 'Marvin Gaye - Whats Going On.jpg', 'marvin gaye', 'what''s going on', 'funk', 'eng', '2021-01-22'),
('The Beach Boys', 'Pet Sounds', 'The Beach Boys - Pet Sounds.jpg', 'the beach boys', 'pet sounds', 'art rock', 'eng', '2012-02-14'),
('Joni Mitchell', 'Blue', 'Joni Mitchell - Blue.jpg', 'joni mitchell', 'blue', 'contemporary folk', 'eng', '2013-05-28'),
('Aretha Franklin', 'I Never Loved a Man the Way I Love You', 'Aretha Franklin - I Never Loved a Man the Way I Love You.jpg', 'aretha franklin', 'i never loved a man the way i love you', 'deep soul', 'eng', '1988-12-21'),
('David Bowie', 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', 'David Bowie - The Rise and Fall of Ziggy Stardust and the Spiders from Mars.jpg', 'david bowie', 'the rise and fall of ziggy stardust and the spiders from mars', 'art rock', 'eng', '2012-06'),
('The Clash', 'London Calling', 'The Clash - London Calling.jpg', 'the clash', 'london calling', 'new wave', 'eng', '2008-12-24'),
('U2', 'The Joshua Tree', 'U2 - The Joshua Tree.jpg', 'u2', 'the joshua tree', 'alternative rock', 'eng', '1987-03-09'),
('Bruce Springsteen', 'Born to Run', 'Bruce Springsteen - Born to Run.jpg', 'bruce springsteen', 'born to run', 'folk rock', 'eng', '1983-10'),
('Radiohead', 'OK Computer', 'Radiohead - OK Computer.jpg', 'radiohead', 'ok computer', 'alternative rock', 'eng', '2016'),
('Kendrick Lamar', 'To Pimp a Butterfly', 'Kendrick Lamar - To Pimp a Butterfly.jpg', 'kendrick lamar', 'to pimp a butterfly', 'conscious hip hop', 'eng', '2015-05-20'),
('Beyoncé', 'Lemonade', 'Beyoncé - Lemonade.jpg', 'beyoncé', 'lemonade', 'alternative r&b', 'eng', '2016-04-23'),
('Adele', '21', 'Adele - 21.jpg', 'adele', '21', 'blue-eyed soul', 'eng', '2011-08-30'),
('Taylor Swift', '1989', 'Taylor Swift - 1989.jpg', 'taylor swift', '1989', 'instrumental', 'eng', '2015-03-03'),
('Jay-Z', 'The Blueprint', 'Jay-Z - The Blueprint.jpg', 'jay-z', 'the blueprint', 'chipmunk soul', 'eng', '2001-09-11'),
('Eminem', 'The Marshall Mathers LP', 'Eminem - The Marshall Mathers LP.jpg', 'eminem', 'the marshall mathers lp', 'hardcore hip hop', 'eng', NULL),
('Dr. Dre', 'The Chronic', 'Dr. Dre - The Chronic.jpg', 'dr. dre', 'the chronic', 'g-funk', 'eng', '2020-04-20'),
('2Pac', 'All Eyez on Me', '2Pac - All Eyez on Me.jpg', '2pac', 'all eyez on me', 'g-funk', 'eng', '1996-03-21'),
('Kanye West', 'My Beautiful Dark Twisted Fantasy', 'Kanye West - My Beautiful Dark Twisted Fantasy.jpg', 'kanye west', 'my beautiful dark twisted fantasy', 'british rhythm & blues', 'eng', '2010-11-22'),
('The Notorious B.I.G.', 'Ready to Die', 'The Notorious B.I.G. - Ready to Die.jpg', 'the notorious b.i.g.', 'ready to die', 'boom bap', 'eng', '2017-09'),
('Metallica', 'Master of Puppets', 'Metallica - Master of Puppets.jpg', 'metallica', 'master of puppets', 'hard rock', 'eng', '2010-09-22'),
('Led Zeppelin', 'Led Zeppelin IV', 'Led Zeppelin - Led Zeppelin IV.jpg', 'led zeppelin', 'led zeppelin iv', 'arena rock', 'eng', NULL),
('Queen', 'A Night at the Opera', 'Queen - A Night at the Opera.jpg', 'queen', 'a night at the opera', 'arena rock', 'eng', '2004-02-11'),
('The Who', 'Who''s Next', 'The Who - Whos Next.jpg', 'the who', 'who''s next', 'ambient', 'eng', NULL),
('The Doors', 'The Doors', 'The Doors - The Doors.jpg', 'the doors', 'the doors', 'avant-garde', 'eng', '2017-02-04'),
('The Velvet Underground', 'The Velvet Underground & Nico', 'The Velvet Underground - The Velvet Underground & Nico.jpg', 'the velvet underground', 'the velvet underground & nico', 'art rock', 'eng', NULL),
('The Smiths', 'The Queen Is Dead', 'The Smiths - The Queen Is Dead.jpg', 'the smiths', 'the queen is dead', 'alternative rock', 'eng', '2017-10-20'),
('Joy Division', 'Unknown Pleasures', 'Joy Division - Unknown Pleasures.jpg', 'joy division', 'unknown pleasures', 'gothic rock', 'eng', '1986'),
('R.E.M.', 'Automatic for the People', 'R.E.M. - Automatic for the People.jpg', 'r.e.m.', 'automatic for the people', 'acoustic rock', 'eng', '1992-10-06'),
('Coldplay', 'A Rush of Blood to the Head', 'Coldplay - A Rush of Blood to the Head.jpg', 'coldplay', 'a rush of blood to the head', 'alternative rock', 'eng', '2002-08'),
('Amy Winehouse', 'Back to Black', 'Amy Winehouse - Back to Black.jpg', 'amy winehouse', 'back to black', 'neo soul', 'eng', '2007-04-30'),
('Lana Del Rey', 'Born to Die', 'Lana Del Rey - Born to Die.jpg', 'lana del rey', 'born to die', 'alternative pop', 'eng', '2012-01-27');
